name: hi

on:
  pull_request:
    branches:
      - main

jobs:
  print_Hi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Print Hi
        run: echo "hi"
